sudo: false
language: node_js
before_install:
  - npm install -g npm
before_script:
  - npm prune
script:
  - npm run validate
after_success:
  - npm run report-coverage
branches:
  only:
    - master
cache:
  directories:
    - node_modules
notifications:
  email: false
